/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AskLuxorRouteImport } from './routes/ask-luxor'
import { Route as AttractionsRouteImport } from './routes/attractions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BazaarsRouteImport } from './routes/bazaars'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as EventsRouteImport } from './routes/events'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as ItinerariesRouteImport } from './routes/itineraries'
import { Route as MapRouteImport } from './routes/map'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiMarketingRouteImport } from './routes/api/marketing'
import { Route as AttractionsSlugRouteImport } from './routes/attractions.$slug'
import { Route as BusinessDashboardRouteImport } from './routes/business.dashboard'
import { Route as BusinessLoginRouteImport } from './routes/business.login'
import { Route as BusinessRegisterRouteImport } from './routes/business.register'
import { Route as BusinessesIdRouteImport } from './routes/businesses.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AskLuxorRoute = AskLuxorRouteImport.update({
  id: '/ask-luxor',
  path: '/ask-luxor',
  getParentRoute: () => rootRouteImport,
} as any)
const AttractionsRoute = AttractionsRouteImport.update({
  id: '/attractions',
  path: '/attractions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BazaarsRoute = BazaarsRouteImport.update({
  id: '/bazaars',
  path: '/bazaars',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesRoute = ItinerariesRouteImport.update({
  id: '/itineraries',
  path: '/itineraries',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketingRoute = ApiMarketingRouteImport.update({
  id: '/api/marketing',
  path: '/api/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AttractionsSlugRoute = AttractionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AttractionsRoute,
} as any)
const BusinessDashboardRoute = BusinessDashboardRouteImport.update({
  id: '/business/dashboard',
  path: '/business/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessLoginRoute = BusinessLoginRouteImport.update({
  id: '/business/login',
  path: '/business/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRegisterRoute = BusinessRegisterRouteImport.update({
  id: '/business/register',
  path: '/business/register',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesIdRoute = BusinessesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BusinessesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ask-luxor': typeof AskLuxorRoute
  '/attractions': typeof AttractionsRouteWithChildren
  '/auth': typeof AuthRoute
  '/bazaars': typeof BazaarsRoute
  '/businesses': typeof BusinessesRouteWithChildren
  '/events': typeof EventsRoute
  '/hotels': typeof HotelsRoute
  '/itineraries': typeof ItinerariesRoute
  '/map': typeof MapRoute
  '/restaurants': typeof RestaurantsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/marketing': typeof ApiMarketingRoute
  '/attractions/$slug': typeof AttractionsSlugRoute
  '/business/dashboard': typeof BusinessDashboardRoute
  '/business/login': typeof BusinessLoginRoute
  '/business/register': typeof BusinessRegisterRoute
  '/businesses/$id': typeof BusinessesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ask-luxor': typeof AskLuxorRoute
  '/attractions': typeof AttractionsRouteWithChildren
  '/auth': typeof AuthRoute
  '/bazaars': typeof BazaarsRoute
  '/businesses': typeof BusinessesRouteWithChildren
  '/events': typeof EventsRoute
  '/hotels': typeof HotelsRoute
  '/itineraries': typeof ItinerariesRoute
  '/map': typeof MapRoute
  '/restaurants': typeof RestaurantsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/marketing': typeof ApiMarketingRoute
  '/attractions/$slug': typeof AttractionsSlugRoute
  '/business/dashboard': typeof BusinessDashboardRoute
  '/business/login': typeof BusinessLoginRoute
  '/business/register': typeof BusinessRegisterRoute
  '/businesses/$id': typeof BusinessesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ask-luxor': typeof AskLuxorRoute
  '/attractions': typeof AttractionsRouteWithChildren
  '/auth': typeof AuthRoute
  '/bazaars': typeof BazaarsRoute
  '/businesses': typeof BusinessesRouteWithChildren
  '/events': typeof EventsRoute
  '/hotels': typeof HotelsRoute
  '/itineraries': typeof ItinerariesRoute
  '/map': typeof MapRoute
  '/restaurants': typeof RestaurantsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/marketing': typeof ApiMarketingRoute
  '/attractions/$slug': typeof AttractionsSlugRoute
  '/business/dashboard': typeof BusinessDashboardRoute
  '/business/login': typeof BusinessLoginRoute
  '/business/register': typeof BusinessRegisterRoute
  '/businesses/$id': typeof BusinessesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ask-luxor'
    | '/attractions'
    | '/auth'
    | '/bazaars'
    | '/businesses'
    | '/events'
    | '/hotels'
    | '/itineraries'
    | '/map'
    | '/restaurants'
    | '/api/chat'
    | '/api/marketing'
    | '/attractions/$slug'
    | '/business/dashboard'
    | '/business/login'
    | '/business/register'
    | '/businesses/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ask-luxor'
    | '/attractions'
    | '/auth'
    | '/bazaars'
    | '/businesses'
    | '/events'
    | '/hotels'
    | '/itineraries'
    | '/map'
    | '/restaurants'
    | '/api/chat'
    | '/api/marketing'
    | '/attractions/$slug'
    | '/business/dashboard'
    | '/business/login'
    | '/business/register'
    | '/businesses/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ask-luxor'
    | '/attractions'
    | '/auth'
    | '/bazaars'
    | '/businesses'
    | '/events'
    | '/hotels'
    | '/itineraries'
    | '/map'
    | '/restaurants'
    | '/api/chat'
    | '/api/marketing'
    | '/attractions/$slug'
    | '/business/dashboard'
    | '/business/login'
    | '/business/register'
    | '/businesses/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AskLuxorRoute: typeof AskLuxorRoute
  AttractionsRoute: typeof AttractionsRouteWithChildren
  AuthRoute: typeof AuthRoute
  BazaarsRoute: typeof BazaarsRoute
  BusinessesRoute: typeof BusinessesRouteWithChildren
  EventsRoute: typeof EventsRoute
  HotelsRoute: typeof HotelsRoute
  ItinerariesRoute: typeof ItinerariesRoute
  MapRoute: typeof MapRoute
  RestaurantsRoute: typeof RestaurantsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiMarketingRoute: typeof ApiMarketingRoute
  BusinessDashboardRoute: typeof BusinessDashboardRoute
  BusinessLoginRoute: typeof BusinessLoginRoute
  BusinessRegisterRoute: typeof BusinessRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-luxor': {
      id: '/ask-luxor'
      path: '/ask-luxor'
      fullPath: '/ask-luxor'
      preLoaderRoute: typeof AskLuxorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attractions': {
      id: '/attractions'
      path: '/attractions'
      fullPath: '/attractions'
      preLoaderRoute: typeof AttractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bazaars': {
      id: '/bazaars'
      path: '/bazaars'
      fullPath: '/bazaars'
      preLoaderRoute: typeof BazaarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries': {
      id: '/itineraries'
      path: '/itineraries'
      fullPath: '/itineraries'
      preLoaderRoute: typeof ItinerariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketing': {
      id: '/api/marketing'
      path: '/api/marketing'
      fullPath: '/api/marketing'
      preLoaderRoute: typeof ApiMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attractions/$slug': {
      id: '/attractions/$slug'
      path: '/$slug'
      fullPath: '/attractions/$slug'
      preLoaderRoute: typeof AttractionsSlugRouteImport
      parentRoute: typeof AttractionsRoute
    }
    '/business/dashboard': {
      id: '/business/dashboard'
      path: '/business/dashboard'
      fullPath: '/business/dashboard'
      preLoaderRoute: typeof BusinessDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/login': {
      id: '/business/login'
      path: '/business/login'
      fullPath: '/business/login'
      preLoaderRoute: typeof BusinessLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/register': {
      id: '/business/register'
      path: '/business/register'
      fullPath: '/business/register'
      preLoaderRoute: typeof BusinessRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/$id': {
      id: '/businesses/$id'
      path: '/$id'
      fullPath: '/businesses/$id'
      preLoaderRoute: typeof BusinessesIdRouteImport
      parentRoute: typeof BusinessesRoute
    }
  }
}

interface AttractionsRouteChildren {
  AttractionsSlugRoute: typeof AttractionsSlugRoute
}

const AttractionsRouteChildren: AttractionsRouteChildren = {
  AttractionsSlugRoute: AttractionsSlugRoute,
}

const AttractionsRouteWithChildren = AttractionsRoute._addFileChildren(
  AttractionsRouteChildren,
)

interface BusinessesRouteChildren {
  BusinessesIdRoute: typeof BusinessesIdRoute
}

const BusinessesRouteChildren: BusinessesRouteChildren = {
  BusinessesIdRoute: BusinessesIdRoute,
}

const BusinessesRouteWithChildren = BusinessesRoute._addFileChildren(
  BusinessesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AskLuxorRoute: AskLuxorRoute,
  AttractionsRoute: AttractionsRouteWithChildren,
  AuthRoute: AuthRoute,
  BazaarsRoute: BazaarsRoute,
  BusinessesRoute: BusinessesRouteWithChildren,
  EventsRoute: EventsRoute,
  HotelsRoute: HotelsRoute,
  ItinerariesRoute: ItinerariesRoute,
  MapRoute: MapRoute,
  RestaurantsRoute: RestaurantsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiMarketingRoute: ApiMarketingRoute,
  BusinessDashboardRoute: BusinessDashboardRoute,
  BusinessLoginRoute: BusinessLoginRoute,
  BusinessRegisterRoute: BusinessRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
